### PR TITLE
Added dynamic forks and stars count

### PR DESCRIPTION
**Pull request by ShivaRapolu01**
Demo: https://www.awesomescreenshot.com/video/11441735?key=e289e1d4df17647a15e9d2f3bcb81909

### CODE REVIEW

**Comment by aditya-singh9** [comment]
Can you make those stars and fork thing in the middle? And responsive

**Comment by aditya-singh9** [comment]
It looks really ugly on phone.

**Comment by ShivaRapolu01** [comment]
Demo: https://www.awesomescreenshot.com/video/11445794?key=fdec9490ba948eb222ae562461b28fb5

**Comment by ShivaRapolu01** [comment]
@aditya-singh9 I am raising PR in the same way but now it is saying authorization required to deploy

**Comment by aditya-singh9** [comment]
Can you make the stars and forks below the heading "shorten urls"
And pls reduce the size of forks and stars thing.

I have taken care of that error.

**Comment by ShivaRapolu01** [comment]
Screenshot from 2022-10-01 19-41-42
I have reduced their size. It is not looking good if I reduce it further

**Comment by ShivaRapolu01** [comment]
@aditya-singh9 please have a look

**Comment by ShivaRapolu01** [comment]
Hey @aditya-singh9 it is showing not accepted and waiting for my 2 Hactoberfest accepted PR's. Please update the status

**Comment by aditya-singh9** [comment]
I am not sure why is it occuring because i have merged your pull request and added the hacktoberfest-accepted lebel too

**Comment by ShivaRapolu01** [comment]
Is it happening the same with other contributers also?

**Pull request merged**
