### PR TITLE
added dark mode

### LINKED ISSUE #16: Add dark and light theme
Add dark and light theme. The user can toggle the button and switch between them.

### PR DESCRIPTION
**Pull request by Anuran12**
Close: #16 

description;-

I added the dark mode and light mode button.

SCREENSHOT 
image

image

### CODE REVIEW

**Comment by aditya-singh9** [comment]
Pls change the fork icon color in dark mode

**Comment by Anuran12** [comment]
> Pls change the fork icon color in dark mode 

okay.... who added that fork and star feature . he used img format for fork logo. can i change that into svg logo ?

**Comment by Anuran12** [comment]
hey... why did you removed the "hacktoberfest-accepted" label ? it will not effect in my hacktoberfest website , right ?

**Comment by aditya-singh9** [comment]
Yes pls
And can you make it something like thr below images

The current ones look big and ugly. Please change them to the ones in [this website](https://kekfinder.ml)

Reference: [kekfinder.ml](https://kekfinder.ml)

**Comment by Anuran12** [comment]
> Yes pls And can you make it something like
> 
> Reference: kekfinder.ml
> 
> 
> 
> 

Okay... with in few minutes bro.. ^_~

**Comment by Anuran12** [comment]
i just solved the fork logo issue .

i am not able to change the style of those star and fork section

i added links on star and fork section

**Comment by Anuran12** [comment]
Please Marge it . I will try to change the style of stars and fork button later

**Pull request merged**
